disabled_rules: # rule identifiers to exclude from running
  - line_length
  - file_length
  - function_body_length
  - vertical_whitespace
  - trailing_whitespace
  - trailing_newline
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Library
identifier_name:
  excluded:
    - id